name: CI/CD

on:
  push:
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    container:
      image: liphium/godot-mono:4.6.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: dotnet format godot-client.sln --verify-no-changes --verbosity diagnostic

      - name: NUnit Test
        run: ls -R

      - name: GdUnit Test
        run: godot --headless --path . -s addons/gdUnit4/bin/GdUnitCmdTool.gd -a res://test